### ISSUE TITLE
Exporting dots… exports circles…

### ISSUE THREAD

**Issue by jimmykl** [ehufsted/HalftonePAL#3]
I'm looking to export just dots. 

I'm going to pen plot the svg and would like each point to be the size of the pen nib.

But when I have Dots selected and export an svg it produces circles. Max radius is as low as it can go (2).

Am I missing a setting somewhere?

**Comment by jimmykl** [comment]
Realised I can workaround this by using illustrator to scale each circle down. But a direct export would be cool if possible.

**Comment by ehufsted** [comment]
It is currently drawing circles rather than single points. I'll work on a better solution.
Sorry for the slow response.

**Comment by ehufsted** [comment]
Should be fixed now!
